Fix mdadm.conf check for know arrays
Fix the check whether mdadm.conf defines all devices known to the system: we
were checking against $devs earlier, which is only those devices required to
boot; $devpairs has them all.

Thanks Cristian Ionescu-Idbohrn.

Debian bug: 525655

Signed-off-by: martin f. krafft <madduck@debian.org>

diff --git a/debian/initramfs/hook b/debian/initramfs/hook
--- a/debian/initramfs/hook
+++ b/debian/initramfs/hook
@@ -24,7 +24,7 @@ is_true()
 {
   case "${1:-}" in
     [Yy]es|[Yy]|1|[Tt]rue|[Tt]) return 0;;
-    *) return 1;
+    *) return 1;;
   esac
 }
 
@@ -234,9 +234,9 @@ if [ "$INITRDSTART" != none ] && [ -n "$devpairs" ]; then
   # see if /etc/mdadm/mdadm.conf looks like it's missing devices
   if [ -x $MDADM ]; then
     $MDADM --detail --scan | while read array device rubbish; do
-      if ! echo $devs | grep -qw $device; then
-        warn "You appear to be missing $device from /etc/mdadm/mdadm.conf"
-        warn "If this is required to boot you must add this line:"
+      if ! echo $devpairs | grep -qw $device; then
+        warn "You appear to be missing $device from /etc/mdadm/mdadm.conf !"
+        warn "If this array is required to boot, you must add the following line:"
         rubbish=`echo $rubbish | sed 's/metadata=[^ ]* //'`
         warn "$array $device $rubbish"
       fi
